export const VALIDATE_DATA_GRAPH_REQUESTED = 'VALIDATE_DATA_GRAPH_REQUESTED' as const;
export const VALIDATE_DATA_GRAPH_SUCCEEDED = 'VALIDATE_DATA_GRAPH_SUCCEEDED' as const;
export const VALIDATE_DATA_GRAPH_FAILED = 'VALIDATE_DATA_GRAPH_FAILED' as const;

export const FETCH_SHAPES_REQUESTED = 'FETCH_SHAPES_REQUESTED' as const;
export const FETCH_SHAPES_SUCCEEDED = 'FETCH_SHAPES_SUCCEEDED' as const;
export const FETCH_SHAPES_FAILED = 'FETCH_SHAPES_FAILED' as const;

export const FETCH_ONTOLOGIES_REQUESTED = 'FETCH_ONTOLOGIES_REQUESTED' as const;
export const FETCH_ONTOLOGIES_SUCCEEDED = 'FETCH_ONTOLOGIES_SUCCEEDED' as const;
export const FETCH_ONTOLOGIES_FAILED = 'FETCH_ONTOLOGIES_FAILED' as const;
