export const VALIDATE_RDF_REQUESTED = 'VALIDATE_RDF_REQUESTED' as const;
export const VALIDATE_RDF_SUCCEEDED = 'VALIDATE_RDF_SUCCEEDED' as const;
export const VALIDATE_RDF_FAILED = 'VALIDATE_RDF_FAILED' as const;
