export const VALIDATE_DATA_GRAPH_REQUESTED = 'VALIDATE_DATA_GRAPH_REQUESTED' as const;
export const VALIDATE_DATA_GRAPH_SUCCEEDED = 'VALIDATE_DATA_GRAPH_SUCCEEDED' as const;
export const VALIDATE_DATA_GRAPH_FAILED = 'VALIDATE_DATA_GRAPH_FAILED' as const;

export const FETCH_SHAPES_COLLECTION_REQUESTED = 'FETCH_SHAPES_COLLECTION_REQUESTED' as const;
export const FETCH_SHAPES_COLLECTION_SUCCEEDED = 'FETCH_SHAPES_COLLECTION_SUCCEEDED' as const;
export const FETCH_SHAPES_COLLECTION_FAILED = 'FETCH_SHAPES_COLLECTION_FAILED' as const;
